### ISSUE TITLE
Please update Overview section on Docker Hub

### ISSUE THREAD

**Issue by michailw** [aeon-php/automation-docker#2]
Could you please update the overview section of the image on Docker Hub?

Currently, it's empty. It would be also nice to publish a link to Github's repository with source code.

You could also connect the Docker hub directly to the Github's repository, so you wouldn't push images manually, they would be built on the Docker hub itself.

![obraz](https://user-images.githubusercontent.com/5175815/103655642-d644f000-4f67-11eb-8680-76baf4dc89f4.png)

**Comment by norberttech** [comment]
https://hub.docker.com/repository/docker/aeonphp/automation done! Thanks, I forgot about this. 

Yeah, I wanted to connect GitHub with aeon but there was a warning that is better to not use the personal account and create a service github account which I will do, but didn't have time yet :P
